name: build addon

on:
  push:
    tags: ["*"]
    # To build on main/master branch, uncomment the following line:
    # branches: [ main , master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python
      run: uv python install

    - name: Install dependencies in Virtual Environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gettext
        uv venv
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        uv pip install Markdown scons pre-commit ruff

    - name: building addon
      run: scons && scons pot

    - uses: actions/upload-artifact@v7
      with:
        name: packaged_addon
        path: |
          ./*.nvda-addon
          ./*.pot

  upload_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    needs: ["build"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6

    - name: download releases files
      uses: actions/download-artifact@v8

    - name: Display structure of downloaded files
      run: ls -R

    - name: Calculate sha256
      run: |
        echo -e "\nSHA256: " >> changelog.md
        sha256sum *.nvda-addon >> changelog.md

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          *.nvda-addon
          *.pot
        body_path: changelog.md
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
